# Generated by Django 5.1.1 on 2024-09-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='specialization',
            field=models.CharField(blank=True),
        ),
    ]
